# Generated by Django 4.1.12 on 2023-11-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombreUsuario', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('passUsuario', models.CharField(max_length=20)),
                ('esConductor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.TimeField()),
                ('lugarInicio', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=30)),
                ('precio', models.PositiveIntegerField()),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('modelo', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
                ('anno', models.IntegerField(max_length=4)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
