# Generated by Django 4.1.12 on 2023-11-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anno',
            field=models.IntegerField(),
        ),
    ]
