# Generated by Django 4.1.12 on 2023-10-31 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugarInicio', models.CharField(max_length=30)),
                ('nomSede', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='core.sede')),
            ],
        ),
    ]
