# Generated by Django 4.1.12 on 2023-11-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vehiculo_anno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='dueño',
        ),
    ]
