# Generated by Django 4.1.12 on 2023-11-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_vehiculo_dueño'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='Usuario',
        ),
    ]
